### ISSUE TITLE
链接可访问性

### ISSUE THREAD

**Issue by YangFong** [rust-lang-cn/rust-by-example-cn#122]
expression 章节，wike 可访问性在此处不合适。可以选择替换，或者参照当前原文更新内容，去除链接。

![image](https://user-images.githubusercontent.com/70502828/150639086-a06c571f-9091-4caf-9d74-d3dfbb1abdc5.png)

**Comment by aaranxu** [comment]
我看了下，是这文件的英文原文有更新了，非常感谢指出！
