### ISSUE TITLE
流程控制章节问题

### ISSUE THREAD

**Issue by YangFong** [rust-lang-cn/rust-by-example-cn#126]
部分问题我无法处理，只能在此说明。

- [x] flow_control/match/destructuring/destructure_tuple - 内容更新（可选）

> 更新内容当中展示了 `..` 的使用，于是我记下来了。

- [x] flow_control/while - 链接可访问性问题
![image](https://user-images.githubusercontent.com/70502828/150741462-f4b855d3-2ac2-4660-8178-1004ac118cef.png)

- [x] flow_control/match - 内容需要更新，去除多出的字
![image](https://user-images.githubusercontent.com/70502828/150741533-1f31eafb-f44b-41f8-9966-9ce648d26be9.png)

- [x] flow_control/match/destructuring/destructure_pointers - 补充参考链接
![image](https://user-images.githubusercontent.com/70502828/150741872-0027f74b-9b3d-4825-9954-371acde58530.png)

- [x] flow_control/match/binding - 翻译可能存在问题（不确定）
![image](https://user-images.githubusercontent.com/70502828/150742078-b727abde-47f9-43b3-bf91-eaeb6d1f0d34.png)

**Comment by aaranxu** [comment]
感谢指出，等有空就更新这些章节。
