### ISSUE TITLE
枚举那小节报错,多了个感叹号

### ISSUE THREAD

**Issue by miguo-app** [rust-lang-cn/rust-by-example-cn#144]
代码第一行
#![allow(dead_code)]
版本1.60
![image](https://user-images.githubusercontent.com/103035502/164913420-3e46203d-39b6-4a71-82f2-27db6704cde8.png)

**Comment by YangFong** [comment]
当前观察，或许此处该做的调整是，进行删除。

![image](https://user-images.githubusercontent.com/70502828/164949097-410d92e7-a435-4912-9c72-7d10f82a7661.png)

**Comment by miguo-app** [comment]
带!感叹号的代码是作用于整个文件的,必须放在第一行,所以代码没有问题.
