### ISSUE TITLE
发现一些正文里边会多出一些空格，不确定是不是设计如此

### ISSUE THREAD

**Issue by weartist** [rust-lang-cn/rust-by-example-cn#159]
例如：https://rustwiki.org/zh-CN/rust-by-example/error/option_unwrap.html
![image](https://user-images.githubusercontent.com/17105034/209637989-3db5a3dd-b95c-493e-a92b-ec88274520a2.png)

查看原始文件发现可能是换行导致的，如果这不是期望的结果，我可以写一个脚本处理并检查一下其他章节

**Comment by YangFong** [comment]
这是换行导致的结果。在英文文档中，是存在单行最大长度的，方便编辑，然而不同的是，英文换行没事，可以当作一个空格，可中文就不一样了。

**Comment by weartist** [comment]
> 这是换行导致的结果。在英文文档中，是存在单行最大长度的，方便编辑，然而不同的是，英文换行没事，可以当作一个空格，可中文就不一样了。

我可以提一个pr改一下吗，如果不需要和英文文档保证格式一样，感觉没有空格会更好一些

**Comment by YangFong** [comment]
因为语言的差异，这种换行导致浏览体验不好，当然是接受改动的。如果有兴趣，可以提 PR 改一改。

**Comment by weartist** [comment]
> 

ok，我试下，感谢你们的翻译！
