### ISSUE TITLE
`指针和引用` 部分代码本地执行报错

### ISSUE THREAD

**Issue by GDdark** [rust-lang-cn/rust-by-example-cn#165]
![image](https://user-images.githubusercontent.com/15982894/217247328-17bb767e-c584-4c08-8d1a-de000e1187ea.png)
![image](https://user-images.githubusercontent.com/15982894/217247555-8c547a56-d95b-4e0b-a056-8439a9bfb12e.png)

Rust 版本：1.61.0

**Comment by YangFong** [comment]
本地测试，1.65.0 未复现成功。后续检查，发现你给 `mut_value` 额外加了一个 `ref`。
