### ISSUE TITLE
From Into描述问题

### ISSUE THREAD

**Issue by katteXu** [rust-lang-cn/rust-by-example-cn#168]
如果我们能够从类型 A 得到类型 B，那么很容易相信我们也能把类型 B 转换为类型 A。
应该更正:
如果我们能够从类型 A 得到类型 B，那么很容易相信我们也能把类型 A 转换为类型 B。

**Comment by YangFong** [comment]
第一，如果 A --> B，那么可以相信 B --> A，这表示转换操作可逆，没有问题。
第二，目前该段的最新原文如下，核心意思没有翻译问题：

> If you are able to convert type A from type B, then it should be easy to believe that we should be able to convert type B to type A.

**Comment by katteXu** [comment]
得到和转化 不就是一个from 和一个 into吗？
翻译成代码的话 不是应该这样吗？
``
struct Number {
    value: i32,
}

impl From<i32> for Number {
    fn from(value: i32) -> Self {
        Number { value }
    }
}


fn main (){
    // 从 10 (A) 得到 Number (B)
    let number = Number::from(10);
    // 将 10 (A) 转化成 Number (B)
    let number2:Number = 10.into();
}
``
翻译成代码  如何从B 到A 呢？

**Comment by katteXu** [comment]
不好意思，好像我说的不够明确

上面已经贴出原文了 
If you are able to convert type A from type B, then it should be easy to believe that we should be able to convert type B to type A.

convert type A from  type B 我理解应该是 从B转化成A  即  B --> A
convert type B to A 也是B转化成A  即B --> A
并不是可逆操作吧

所以我提出要改正的 应该是：
如果我们能够从类型 B 得到类型 A，那么很容易相信我们也能把类型 B 转换为类型 A。

这样是否能够理解呢？

**Comment by YangFong** [comment]
综合所述，你的解释没问题，这一段有误区，我将修正这一段。
