### ISSUE TITLE
翻译建议

### ISSUE THREAD

**Issue by pearzl** [rust-lang-cn/rust-by-example-cn#19]
在 `7.2.1嵌套循环和标签` 里面，下面这个句子似乎不太通顺

> 并且标签必须给 break/continue 语句通过（the label must be passed to the break/continue statement.）

感觉pass应该翻译成`传递`更合适
> 并且标签必须传递给break/continue 语句。

**Comment by aakloxu** [comment]
非常感谢，已改过来了~

**Comment by pearzl** [comment]
嗯，太好了。我看这么久没有回应还以为没人维护了呢。哈哈。

**Comment by aakloxu** [comment]
确实如你所说，有一些语句在翻译过程中斟酌很久也还没找到好的译法，所以就先保留原文，一是在后续对这些语句逐步找到更好的翻译然后替换上，另一方面也可以让其他读者在看到这些有问题的翻译时，可以从原文中找到更准确的表达，要是能提供更好的表达方式最好不过了。
