### ISSUE TITLE
Add translation into the official repository

### ISSUE THREAD

**Issue by dalance** [rust-lang-cn/rust-by-example-cn#196]
This is only suggestion.
I'm a contributer of Japanese translation of RBE, and worked to merge Japanese translation into the official repository.
I think merging into the official has some advantages than the independent repository.

* [As translator] Fixes in the official will be reflected immediately
* [As translator] Tracking the official and searching the changes are not required
* [As user] The official URL (https://doc.rust-lang.org/rust-by-example/) can be used
* [As user] Through language selector in the page, language can be changed like from your language to English and vise versa

If you are interesting in this suggestion, please see https://github.com/rust-lang/rust-by-example/blob/master/TRANSLATING.md.
I can support you, if you have any question.

**Comment by Binlogo** [comment]
> This is only suggestion. I'm a contributer of Japanese translation of RBE, and worked to merge Japanese translation into the official repository. I think merging into the official has some advantages than the independent repository.
> 
> * [As translator] Fixes in the official will be reflected immediately
> * [As translator] Tracking the official and searching the changes are not required
> * [As user] The official URL (https://doc.rust-lang.org/rust-by-example/) can be used
> * [As user] Through language selector in the page, language can be changed like from your language to English and vise versa
> 
> If you are interesting in this suggestion, please see https://github.com/rust-lang/rust-by-example/blob/master/TRANSLATING.md. I can support you, if you have any question.

Awesome job and great suggestion 👍. Thank you for bringing this up. I believe that multi-language official support for Rust books, especially for entry-level resources like RBE, will significantly enhance the learning experience for users. With the language selector on the page, users can more easily stay updated with the latest English version. I'd like to help here.

cc @YangFong What do you think?

**Comment by YangFong** [comment]
It's fun, I'll try it.

**Comment by Binlogo** [comment]
@YangFong Great, thanks for your reply and I'm glad you're interested as well. Following @dalance's suggestion and guidance, I've started a try. Here's some research for your information:

**Current Status**
- This [rust-by-example-cn repo](https://github.com/rust-lang-cn/rust-by-example-cn) is not a fork of the original official source. It has significantly enhanced the user experience and differs greatly from the upstream version.
-  According to [TRANSLATING.md](https://github.com/rust-lang/rust-by-example/blob/master/TRANSLATING.md) at the official repo, it uses the [Gettext](https://www.gnu.org/software/gettext/manual/html_node/index.html) system for translations, making it difficult to easily import and use our existing translations.

Therefore, merging this repo directly into the official repository is challenging. I've initiated [a fork](https://github.com/Binlogo/rust-by-example/tree/translation-zh) from the original repository to prepare for adding a Chinese translation.

**Declaration**: I am not currently a member of the [rust-lang-cn] organization, so I forked it under my personal account. However, I highly recommend that we create a new fork directly from the official repository. @YangFong, if possible, let's transform the current [`Binlogo/rust-by-example`](https://github.com/Binlogo/rust-by-example/tree/translation-zh) into the [rust-lang-cn] organization as [`rust-lang-cn/rust-by-example`], allowing us to collaborate on the new repo and add the Chinese translation to the official repository together.

---

**Actions Tracking**

Steps & Progress:
-  [x] Followed [RBE Translation Guideline](https://github.com/rust-lang/rust-by-example/blob/master/TRANSLATING.md) to create the Chinese (`zh`) language ✅ 2024-08-17
-  [ ] Update `./po/zh.po` to Chinese
    - Refer to [简介 - 通过例子学 Rust 中文版](https://rustwiki.org/zh-CN/rust-by-example)
    - Refer to [Rust 语言术语中英文对照表 | Rust 文档网](https://rustwiki.org/wiki/translate/english-chinese-glossary-of-rust/) ⭐️
    - [x] src/SUMMARY.md ✅ 2024-08-17
    - [x] src/index.md ✅ 2024-08-17
    - [x] src/hello/comment.md ✅ 2024-08-17

Conflict Issues Tracking:
-  [ ] `Guards`: 卫语句 vs. **守卫**
-  [ ] `Where clauses`: 子句 vs. **分句**

**Comment by YangFong** [comment]
@Binlogo Ok, I invite you to join the organization, please check whether you can fork your branch into the organization, if not, please contact me, I will fork the operation. Thank you for your help.

**Comment by mgeisler** [comment]
> * According to [TRANSLATING.md](https://github.com/rust-lang/rust-by-example/blob/master/TRANSLATING.md) at the official repo, it uses the [Gettext](https://www.gnu.org/software/gettext/manual/html_node/index.html) system for translations, making it difficult to easily import and use our existing translations.

Hi there :wave: :smile: I developed the mdbook-i18n-helpers plugin used by the Japanese translation.

Converting two Markdown files (in two different languages, say, English and Chinese) back to a PO file is something we have looked at https://github.com/google/mdbook-i18n-helpers/issues/30.

It is not something that can be 100% automated, but it should be possible to write a tool that will match up distinctive markers such as headings and list items and then use this to guess what belong together.

The output would be a rough starting point. Even with perfect matching, mdbook-i18n-helpers requires the original language to be the source of truth. This means that if there are completely new pages in the Chinese translation, then _they will disappear_ unless you write an English page to "attach" it to. The same happens on the level of headings, list items, and even individual table cells.

I ran into this for Comprehensive Rust and worked with the translators to "port" their additions back to the English text. It's basically a more strict system than a free-form clone.

**Comment by Binlogo** [comment]
Following the guidance from [Rust by Example's translation instructions](https://github.com/rust-lang/rust-by-example/blob/master/TRANSLATING.md), all steps have been completed, and the RBE Chinese translation has been deployed [nightly](https://doc.rust-lang.org/nightly/rust-by-example/zh/index.html). We can now close this issue and mark it as resolved. 🎉
