### ISSUE TITLE
====== 证书问题导致无法在chrome中访问 ========

### ISSUE THREAD

**Issue by FreeWong** [rust-lang-cn/rust-by-example-cn#67]
https://rustwiki.org/zh-CN/rust-by-example/
在Chrome中无法访问了，最近几天都是这个情况
感谢您的辛勤工作!!

**Comment by zombie110year** [comment]
> 各个网站通过证书证明自己的身份，它们在设定的时间段内有效。rustwiki.org 的证书已于 2019/10/22 过期。
> 
> 错误代码：SEC_ERROR_EXPIRED_CERTIFICATE

HTTPS 证书该更新了。

**Comment by zombie110year** [comment]
> 
> 
> [rustwiki.org/zh-CN/rust-by-example](https://rustwiki.org/zh-CN/rust-by-example/)
> 在Chrome中无法访问了，最近几天都是这个情况
> 感谢您的辛勤工作!!

你暂时可以选择忽略警告继续访问。

**Comment by aaranxu** [comment]
已经处理，谢谢提醒~

**Comment by mantou132** [comment]
证书又过期了。
