### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by jjakj1** [rust-lang-cn/rust-by-example-cn#79]
您好，在`From`和`Into`一节内容中的第一段后半部分原文为：If you are able to convert type A from type B, then it should be easy to believe that we should be able to convert type B to type A. 应该都是再说B转换到A，我认为翻译为：如果我们能够从类型B得到类型A，那么很容易相信我们也能把类型B转换为类型A。会更加合理。望采纳。

**Comment by aaranxu** [comment]
非常感谢~
